# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Jo0JR5sKLSA7jhmV3ZJXFTiI5yryzhI+AXPrcqJ0S2AoICqA3hCG2IFUqgwKvEx8UZbbD/LB/562e00lq2wWZ5iAgkoRWvoMwV11r8lUxq1SpuAJNtI0oOyMIgtYixtqnbHBWAvtiwHCG2Pav0CxCorzPTphXu4IH27mldeief7gL0jAVn18GXXIjZv0PawhF2W6+wB/5NniqpkgYZ6e8YE6Q6k5zX3rwUzHmWeG0ffpYEotjSEmR7K2dfGC4LCYuWwM5j/UW76qws11GaAHUPRfiV1ThtWuRkbWqPykPGCkARDikKUxNg6ksdRvOlaD9IvwnkIZ+AUvkNUf4498ubq4XbDqvnBj7hmqlus1EsCjrazy+R03iWFFiR8VTKpoZ3GdQ2uyPS+WlQJCrnGN23VpPKYRNHJTm2ACgVCrp+hQrkRJvPh5lkiubcFJLp1AbRWQNYEJC24JdwkjyEA/nK5FDnTMw5jqLfeeDmjjAcDCuoDiuTRDKm/eUH0mv034KK35VJS2nL70Ir+5rn8mToYNLXuv18Nw6jpuWqFW/fgW6H+F4lVSoaOuP1Z43Ep5v2EGRwXO8j7qzu2iXBlkeznvYCCRGRxVv9a1BJMxCTyUeY0hbueBeAeBvU80xk68GhxfBTrErPJ636jWhWJ3L84iU0g9tlObOaDAsVHmhRM="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
