travis:
  secure:
    BINSTAR_TOKEN: Jo0JR5sKLSA7jhmV3ZJXFTiI5yryzhI+AXPrcqJ0S2AoICqA3hCG2IFUqgwKvEx8UZbbD/LB/562e00lq2wWZ5iAgkoRWvoMwV11r8lUxq1SpuAJNtI0oOyMIgtYixtqnbHBWAvtiwHCG2Pav0CxCorzPTphXu4IH27mldeief7gL0jAVn18GXXIjZv0PawhF2W6+wB/5NniqpkgYZ6e8YE6Q6k5zX3rwUzHmWeG0ffpYEotjSEmR7K2dfGC4LCYuWwM5j/UW76qws11GaAHUPRfiV1ThtWuRkbWqPykPGCkARDikKUxNg6ksdRvOlaD9IvwnkIZ+AUvkNUf4498ubq4XbDqvnBj7hmqlus1EsCjrazy+R03iWFFiR8VTKpoZ3GdQ2uyPS+WlQJCrnGN23VpPKYRNHJTm2ACgVCrp+hQrkRJvPh5lkiubcFJLp1AbRWQNYEJC24JdwkjyEA/nK5FDnTMw5jqLfeeDmjjAcDCuoDiuTRDKm/eUH0mv034KK35VJS2nL70Ir+5rn8mToYNLXuv18Nw6jpuWqFW/fgW6H+F4lVSoaOuP1Z43Ep5v2EGRwXO8j7qzu2iXBlkeznvYCCRGRxVv9a1BJMxCTyUeY0hbueBeAeBvU80xk68GhxfBTrErPJ636jWhWJ3L84iU0g9tlObOaDAsVHmhRM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
